service: lambda-layers-with-hug

provider:
  name: aws
  runtime: python3.7

layers:
  hug:
    path: layers/hug
    allowedAccounts:
      - '*'
    compatibleRuntimes:
      - python3.7

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.__hug_wsgi__
    packRequirements: false
  pythonRequirements:
    dockerizePip: true

functions:
  app:
    handler: wsgi_handler.handler
    layers:
      - { Ref: HugLambdaLayer }
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
